module.exports = {
  UPDATE_EDIT_MODE: 'UPDATE_EDIT_MODE',
  UPDATE_LEFT_BUTTONS: 'UPDATE_LEFT_BUTTONS',
  UPDATE_RIGHT_BUTTONS: 'UPDATE_RIGHT_BUTTONS',
  COMPONENT_SELECT: 'COMPONENT_SELECT',
  INSERT_ROW: 'INSERT_ROW',
  DELETE_ROW: 'DELETE_ROW',
  UPDATE_PAGE_TITLE: 'UPDATE_PAGE_TITLE',
  UPDATE_CELL: 'UPDATE_CELL',
  PASTE: 'PASTE',
  COPY: 'COPY'
};
