module.exports = {
  UNDO: 'UNDO',
  REDO: 'REDO',
  DELETE: 'DELETE',
  UPDATE_VALUE: 'UPDATE_VALUE',
  UPDATE_EDIT_MODE: 'UPDATE_PAGE_INFO',
  UPDATE_LEFT_BUTTONS: 'UPDATE_LEFT_BUTTONS',
  UPDATE_RIGHT_BUTTONS: 'UPDATE_RIGHT_BUTTONS',
  COMPONENT_SELECT: 'COMPONENT_SELECT',
  INSERT_ROW: 'INSERT_ROW',
  DELETE_ROW: 'DELETE_ROW',
  UPDATE_CELL: 'UPDATE_CELL',
  PASTE: 'PASTE',
  COPY: 'COPY'
};
